table configuraciones {

  id int [pk,increment]
  nombre varchar
  descripcion varchar
  direccion varchar
  telefono varchar
  divisa varchar
  correo_electronico varchar
  web varchar
  logo varchar

}

table gestiones {
  id int [pk, increment]
  nombre varchar
}

table periodos {
  id int [pk, increment]
  nombre varchar
  gestion_id int [ref: > gestiones.id]
}

table niveles {
  id int [pk,increment]
  nombre varchar
}

table grados {
  id int [pk,increment]
  nombre varchar
  nivel_id int [ref: > niveles.id]
}

table paralelos {
  id int [pk,increment]
  nombre varchar
  grado_id int [ref: > grados.id]
}

table turnos {
  id int [pk,increment]
  nombre varchar
}

table materias {
  id int [pk,increment]
  nombre varchar
}

table users {
  id int [pk,increment]
  name varchar
  email varchar
  password varchar
}

table personals{
  id int [pk,increment]
  usuario_id int [ref: > users.id]
  tipo varchar
  nombre varchar
  apellidos varchar
  ci varchar
  fecha_nacimiento date
  direccion varchar
  telefono varchar
  profesion varchar
  foto varchar
}