table configuraciones {

  id int [pk,increment]
  nombre varchar
  descripcion varchar
  direccion varchar
  telefono varchar
  divisa varchar
  correo_electronico varchar
  web varchar
  logo varchar

}

 table gestiones{
  id int [pk, increment]
  nombre varchar
 }